apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: echobot
  namespace: gitops-series
spec:
  interval: 1m
  url: git@github.com:sngular/gitops-echobot.git
  ref:
    branch: develop

